### ISSUE TITLE
Suggest to loosen the dependency on notion

### ISSUE THREAD

**Issue by Agnes-U** [wcchristian/gh-action-notion-card#5]
Hi, your project gh-action-notion-card(commit id: 6412c6a99467c0115eb4ec3d9c5a842712ecb206) requires "notion==0.0.20" in its dependency. After analyzing the source code, we found that the following versions of notion can also be suitable, i.e., notion 0.0.21, since all functions that you directly (2 APIs: notion.client.NotionClient.__init__, notion.client.NotionClient.get_collection_view) or indirectly (propagate to 29 notion's internal APIs and 20 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on notion from "notion==0.0.20" to "notion>=0.0.20,<=0.0.21". This will improve the applicability of gh-action-notion-card and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on notion?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by wcchristian** [comment]
Sure thing, you can go for a PR if you'd like!. Otherwise when I get time (not sure when) I may refactor to use Notion's actual API rather than the python client / unofficial API.

**Comment by Agnes-U** [comment]
Thanks, here's the [PR](https://github.com/wcchristian/gh-action-notion-card/pull/6).

**Comment by wcchristian** [comment]
PR Merged, thanks!
